<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="130" started-at="2017-12-30T19:49:37Z" finished-at="2017-12-30T19:49:37Z">
    <groups>
      <group name="Regression">
        <method signature="TestNGSessionTwo.testcase011()[pri:1, instance:MavenProject.MavenDec2017.TestNGSessionTwo@6442b0a6]" name="testcase011" class="MavenProject.MavenDec2017.TestNGSessionTwo"/>
        <method signature="TestNGSessionTwo.testcase012()[pri:2, instance:MavenProject.MavenDec2017.TestNGSessionTwo@6442b0a6]" name="testcase012" class="MavenProject.MavenDec2017.TestNGSessionTwo"/>
        <method signature="TestNGSessionTwo.testcase013(java.lang.String, java.lang.String)[pri:3, instance:MavenProject.MavenDec2017.TestNGSessionTwo@6442b0a6]" name="testcase013" class="MavenProject.MavenDec2017.TestNGSessionTwo"/>
      </group> <!-- Regression -->
    </groups>
    <test name="Test" duration-ms="130" started-at="2017-12-30T19:49:37Z" finished-at="2017-12-30T19:49:37Z">
      <class name="MavenProject.MavenDec2017.TestNGSessionTwo">
        <test-method status="FAIL" signature="testcase011()[pri:1, instance:MavenProject.MavenDec2017.TestNGSessionTwo@6442b0a6]" name="testcase011" duration-ms="50" started-at="2017-12-30T14:49:37Z" description="Login Testcase" finished-at="2017-12-30T14:49:37Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at MavenProject.MavenDec2017.TestNGSessionTwo.testcase011(TestNGSessionTwo.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase011 -->
        <test-method status="PASS" signature="testcase013(java.lang.String, java.lang.String)[pri:3, instance:MavenProject.MavenDec2017.TestNGSessionTwo@6442b0a6]" name="testcase013" duration-ms="1" started-at="2017-12-30T14:49:37Z" description="Testcase Parameter" finished-at="2017-12-30T14:49:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ASVG]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[15]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase013 -->
        <test-method status="SKIP" signature="testcase012()[pri:2, instance:MavenProject.MavenDec2017.TestNGSessionTwo@6442b0a6]" name="testcase012" duration-ms="0" started-at="2017-12-30T14:49:37Z" description="Logout Testcase" depends-on-methods="MavenProject.MavenDec2017.TestNGSessionTwo.testcase011" finished-at="2017-12-30T14:49:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestNGSessionTwo.testcase012()[pri:2, instance:MavenProject.MavenDec2017.TestNGSessionTwo@6442b0a6] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestNGSessionTwo.testcase012()[pri:2, instance:MavenProject.MavenDec2017.TestNGSessionTwo@6442b0a6] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase012 -->
      </class> <!-- MavenProject.MavenDec2017.TestNGSessionTwo -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
